@HostAddress = https://localhost:7000

GET {{HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{HostAddress}}/api/students
Accept: application/json

###

GET {{HostAddress}}/api/students/134
Accept: application/json

###

POST {{HostAddress}}/api/students
Content-type: application/json
{
  "PIN": 789,
  "First_name":"Toph",
  "Last_name":"Beifong"
}

###

PUT {{HostAddress}}/api/students/345
Content-type: application/json
{
  "PIN":345,
  "First_Name":"Duncan",
  "Last_Name":"Idaho"
}

###

DELETE {{HostAddress}}/api/students/345
Accept: application/json

###

GET {{HostAddress}}/api/instructors
Accept: application/json

###

GET {{HostAddress}}/api/instructors/2
Accept: application/json

###

POST {{HostAddress}}/api/instructors
Content-type: application/json
{
  "Id": 6,
  "First_name": "Jesus",
  "Last_name": "Christ"
}

###

PUT {{HostAddress}}/api/instructors/4
Content-Type: application/json
{
  "Id":6,
  "First_name": "Michael",
  "Last_name": "Morningstar"
}

###

DELETE {{HostAddress}}/api/instructors/5
Accept: application/json