@HostAddress = https://localhost:7000


GET {{HostAddress}}/api/students
Accept: application/json

###

GET {{HostAddress}}/api/students/hjPe23Lmn4
Accept: application/json

###

POST {{HostAddress}}/api/students/sdgr34Pwn6/course/1
Accept: application/json

###

POST {{HostAddress}}/api/students
Content-type: application/json
{
  "PIN": "sdgr34Pwn6",
  "First_name":"Toph",
  "Last_name":"Beifong"
}

###

PUT {{HostAddress}}/api/students/oopq34dda5
Content-type: application/json
{
  "PIN":"oopq34dda5",
  "First_Name":"Duncan",
  "Last_Name":"Idaho"
}

###

DELETE {{HostAddress}}/api/students/oopq34dda5
Accept: application/json

###

GET {{HostAddress}}/api/instructors
Accept: application/json

###

GET {{HostAddress}}/api/instructors/2
Accept: application/json

###

POST {{HostAddress}}/api/instructors
Content-type: application/json
{
  "First_name": "Jesus",
  "Last_name": "Christ"
}

###

PUT {{HostAddress}}/api/instructors/4
Content-Type: application/json
{
  "Id":6,
  "First_name": "Michael",
  "Last_name": "Morningstar"
}

###

DELETE {{HostAddress}}/api/instructors/6
Accept: application/json

###

GET {{HostAddress}}/api/courses
Accept: application/json

###

GET {{HostAddress}}/api/courses/3
Accept: application/json

###
POST {{HostAddress}}/api/courses
Content-Type: application/json
{
  "Id": 6,
  "name": "Spice",
  "instructor_id": 3,
  "Total_time": 13,
  "Credit": 1
}

###
PUT {{HostAddress}}/api/courses/3
Content-type: application/json
{
  "Id": 3,
  "Name": "Mssdasaw",
  "Instructor_id": 4,
  "Total_time": 22,
  "Credit": 33
}

###

DELETE {{HostAddress}}/api/courses/6
Accept: application/json