// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Technical_Request.Data;

#nullable disable

namespace Technical_Request.Migrations
{
    [DbContext(typeof(TechnicalRequestContext))]
    [Migration("20251209142913_Seed Extra Data")]
    partial class SeedExtraData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Technical_Request.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2344",
                            Name = "Block-1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "24312",
                            Name = "Block-2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "2554",
                            Name = "Block-3"
                        },
                        new
                        {
                            Id = 4,
                            Code = "2332",
                            Name = "Block-4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "2445",
                            Name = "Block-5"
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PIN", "DateAdded")
                        .IsUnique()
                        .IsDescending(false, true)
                        .HasFilter("[PIN] IS NOT NULL AND [DateAdded] IS NOT NULL");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateAdded = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Connor",
                            PIN = "2245666422",
                            Surname = "Leo"
                        },
                        new
                        {
                            Id = 2,
                            DateAdded = new DateTime(2023, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Anton",
                            LastName = "Milev",
                            PIN = "2243211422",
                            Surname = "Tsvyatkov"
                        },
                        new
                        {
                            Id = 3,
                            DateAdded = new DateTime(2021, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Hristo",
                            LastName = "Kirilov",
                            PIN = "2245663222",
                            Surname = "Pavlov"
                        },
                        new
                        {
                            Id = 4,
                            DateAdded = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            LastName = "Johnson",
                            PIN = "2245556422",
                            Surname = "Johnathan"
                        },
                        new
                        {
                            Id = 5,
                            DateAdded = new DateTime(2024, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mathew",
                            LastName = "Powel",
                            PIN = "2245006422",
                            Surname = "Jacob"
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.EmployeeView", b =>
                {
                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("ResponsiblePersonActivities", (string)null);
                });

            modelBuilder.Entity("Technical_Request.Models.ResponsiblePerson", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "Activity");

                    b.HasIndex("ServiceId", "Activity")
                        .IsUnique();

                    b.ToTable("ResponsiblePersons");

                    b.HasData(
                        new
                        {
                            ServiceId = 3,
                            Activity = "creation",
                            EmployeeId = 1
                        },
                        new
                        {
                            ServiceId = 2,
                            Activity = "creation",
                            EmployeeId = 5
                        },
                        new
                        {
                            ServiceId = 5,
                            Activity = "creation",
                            EmployeeId = 1
                        },
                        new
                        {
                            ServiceId = 5,
                            Activity = "confirmation",
                            EmployeeId = 1
                        },
                        new
                        {
                            ServiceId = 2,
                            Activity = "confirmation",
                            EmployeeId = 3
                        },
                        new
                        {
                            ServiceId = 1,
                            Activity = "confirmation",
                            EmployeeId = 4
                        },
                        new
                        {
                            ServiceId = 1,
                            Activity = "approval",
                            EmployeeId = 1
                        },
                        new
                        {
                            ServiceId = 2,
                            Activity = "approval",
                            EmployeeId = 2
                        },
                        new
                        {
                            ServiceId = 3,
                            Activity = "approval",
                            EmployeeId = 5
                        },
                        new
                        {
                            ServiceId = 5,
                            Activity = "verification",
                            EmployeeId = 2
                        },
                        new
                        {
                            ServiceId = 3,
                            Activity = "verification",
                            EmployeeId = 2
                        },
                        new
                        {
                            ServiceId = 4,
                            Activity = "verification",
                            EmployeeId = 4
                        },
                        new
                        {
                            ServiceId = 2,
                            Activity = "verification",
                            EmployeeId = 3
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.ServiceBlock", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "BlockId");

                    b.ToTable("ServiceBlocks");

                    b.HasData(
                        new
                        {
                            ServiceId = 4,
                            BlockId = 5
                        },
                        new
                        {
                            ServiceId = 2,
                            BlockId = 2
                        },
                        new
                        {
                            ServiceId = 4,
                            BlockId = 4
                        },
                        new
                        {
                            ServiceId = 2,
                            BlockId = 3
                        },
                        new
                        {
                            ServiceId = 1,
                            BlockId = 1
                        },
                        new
                        {
                            ServiceId = 2,
                            BlockId = 4
                        },
                        new
                        {
                            ServiceId = 4,
                            BlockId = 3
                        },
                        new
                        {
                            ServiceId = 5,
                            BlockId = 2
                        },
                        new
                        {
                            ServiceId = 1,
                            BlockId = 5
                        },
                        new
                        {
                            ServiceId = 1,
                            BlockId = 3
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.ServiceSystem", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "SystemId");

                    b.ToTable("ServiceSystems");

                    b.HasData(
                        new
                        {
                            ServiceId = 3,
                            SystemId = 3
                        },
                        new
                        {
                            ServiceId = 5,
                            SystemId = 2
                        },
                        new
                        {
                            ServiceId = 5,
                            SystemId = 1
                        },
                        new
                        {
                            ServiceId = 3,
                            SystemId = 4
                        },
                        new
                        {
                            ServiceId = 5,
                            SystemId = 5
                        },
                        new
                        {
                            ServiceId = 2,
                            SystemId = 1
                        },
                        new
                        {
                            ServiceId = 4,
                            SystemId = 4
                        },
                        new
                        {
                            ServiceId = 5,
                            SystemId = 3
                        },
                        new
                        {
                            ServiceId = 4,
                            SystemId = 1
                        },
                        new
                        {
                            ServiceId = 2,
                            SystemId = 3
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Systems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2245",
                            Name = "System 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2145",
                            Name = "System 2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "2945",
                            Name = "System 3",
                            Parent = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "2545",
                            Name = "System 4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "3245",
                            Name = "System 5",
                            Parent = 3
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.TechnicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TechnicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Desc",
                            Name = "Service 1",
                            TimeOfCreation = new DateTime(2025, 12, 9, 16, 29, 12, 800, DateTimeKind.Local).AddTicks(1548)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descr",
                            Name = "Service 2",
                            TimeOfCreation = new DateTime(2025, 12, 9, 16, 29, 12, 801, DateTimeKind.Local).AddTicks(3861)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descri",
                            Name = "Service 3",
                            TimeOfCreation = new DateTime(2025, 12, 9, 16, 29, 12, 801, DateTimeKind.Local).AddTicks(3876)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Descrip",
                            Name = "Service 4",
                            TimeOfCreation = new DateTime(2025, 12, 9, 16, 29, 12, 801, DateTimeKind.Local).AddTicks(3878)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Descript",
                            Name = "Service 5",
                            TimeOfCreation = new DateTime(2025, 12, 9, 16, 29, 12, 801, DateTimeKind.Local).AddTicks(3879)
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
