// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Technical_Request.Data;

#nullable disable

namespace Technical_Request.Migrations
{
    [DbContext(typeof(TechnicalRequestContext))]
    partial class TechnicalRequestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Technical_Request.Models.Block", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Blocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2344",
                            Name = "Block-1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "24312",
                            Name = "Block-2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "2554",
                            Name = "Block-3"
                        },
                        new
                        {
                            Id = 4,
                            Code = "2332",
                            Name = "Block-4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "2445",
                            Name = "Block-5"
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PIN")
                        .IsUnique();

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "John",
                            LastName = "Connor",
                            PIN = "2245666422",
                            Surname = "Leo"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "Anton",
                            LastName = "Milev",
                            PIN = "2243211422",
                            Surname = "Tsvyatkov"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Hristo",
                            LastName = "Kirilov",
                            PIN = "2245663222",
                            Surname = "Pavlov"
                        },
                        new
                        {
                            Id = 4,
                            FirstName = "John",
                            LastName = "Johnson",
                            PIN = "2245556422",
                            Surname = "Johnathan"
                        },
                        new
                        {
                            Id = 5,
                            FirstName = "Mathew",
                            LastName = "Powel",
                            PIN = "2245006422",
                            Surname = "Jacob"
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.ResponsiblePerson", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ServiceId", "EmployeeId");

                    b.HasIndex("EmployeeId", "ServiceId", "Activity")
                        .IsUnique();

                    b.ToTable("ResponsiblePersons");
                });

            modelBuilder.Entity("Technical_Request.Models.ServiceBlock", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("BlockId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "BlockId");

                    b.ToTable("ServiceBlocks");
                });

            modelBuilder.Entity("Technical_Request.Models.ServiceSystem", b =>
                {
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("SystemId")
                        .HasColumnType("int");

                    b.HasKey("ServiceId", "SystemId");

                    b.ToTable("ServiceSystems");
                });

            modelBuilder.Entity("Technical_Request.Models.System", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Systems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "2245",
                            Name = "System 1"
                        },
                        new
                        {
                            Id = 2,
                            Code = "2145",
                            Name = "System 2"
                        },
                        new
                        {
                            Id = 3,
                            Code = "2945",
                            Name = "System 3",
                            Parent = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "2545",
                            Name = "System 4"
                        },
                        new
                        {
                            Id = 5,
                            Code = "3245",
                            Name = "System 5",
                            Parent = 3
                        });
                });

            modelBuilder.Entity("Technical_Request.Models.TechnicalService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeOfCreation")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TechnicalServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Desc",
                            Name = "Service 1",
                            TimeOfCreation = new DateTime(2025, 12, 5, 17, 58, 58, 92, DateTimeKind.Local).AddTicks(1883)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descr",
                            Name = "Service 2",
                            TimeOfCreation = new DateTime(2025, 12, 5, 17, 58, 58, 93, DateTimeKind.Local).AddTicks(3602)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descri",
                            Name = "Service 3",
                            TimeOfCreation = new DateTime(2025, 12, 5, 17, 58, 58, 93, DateTimeKind.Local).AddTicks(3614)
                        },
                        new
                        {
                            Id = 4,
                            Description = "Descrip",
                            Name = "Service 4",
                            TimeOfCreation = new DateTime(2025, 12, 5, 17, 58, 58, 93, DateTimeKind.Local).AddTicks(3617)
                        },
                        new
                        {
                            Id = 5,
                            Description = "Descript",
                            Name = "Service 5",
                            TimeOfCreation = new DateTime(2025, 12, 5, 17, 58, 58, 93, DateTimeKind.Local).AddTicks(3618)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
