// <auto-generated />
using System;
using Coursera_Exercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coursera_Exercise.Migrations
{
    [DbContext(typeof(CourseraExerciseContext))]
    [Migration("20251128131814_CreateSP")]
    partial class CreateSP
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Coursera_Exercise.DB_Views.CourseDetails", b =>
                {
                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<string>("Course_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Credit")
                        .HasColumnType("smallint");

                    b.Property<string>("Instructor_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Total_time")
                        .HasColumnType("smallint");

                    b.ToTable((string)null);

                    b.ToView("CourseDetails", (string)null);
                });

            modelBuilder.Entity("Coursera_Exercise.DB_Views.StudentCredit", b =>
                {
                    b.Property<string>("Student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Student_PIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Credit")
                        .HasColumnType("int");

                    b.ToTable((string)null);

                    b.ToView("StudentCredits", (string)null);
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Credit")
                        .HasColumnType("smallint");

                    b.Property<int>("Instructor_id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.Property<short>("Total_time")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Instructor_id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Credit = (short)20,
                            Instructor_id = 3,
                            Name = "Programming basics",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_time = (short)23
                        },
                        new
                        {
                            Id = 2,
                            Credit = (short)1,
                            Instructor_id = 3,
                            Name = "Object orianted programming",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_time = (short)13
                        },
                        new
                        {
                            Id = 3,
                            Credit = (short)22,
                            Instructor_id = 2,
                            Name = "Parody",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_time = (short)22
                        },
                        new
                        {
                            Id = 4,
                            Credit = (short)9,
                            Instructor_id = 5,
                            Name = "Creative Writing",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_time = (short)43
                        },
                        new
                        {
                            Id = 5,
                            Credit = (short)23,
                            Instructor_id = 1,
                            Name = "Elvish",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Total_time = (short)34
                        });
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("First_name", "Last_name")
                        .IsUnique();

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            First_name = "Gandalf",
                            Last_name = "The Gray",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            First_name = "Moiraine",
                            Last_name = "Sedai",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            First_name = "Leto Atreides",
                            Last_name = "The Second The Second",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            First_name = "Archangel",
                            Last_name = "Michael",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            First_name = "Eda",
                            Last_name = "Clawthorne",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Student", b =>
                {
                    b.Property<string>("PIN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("First_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Time_created")
                        .HasColumnType("datetime2");

                    b.HasKey("PIN");

                    b.HasIndex("First_name", "Last_name")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            PIN = "sahh12KJF3",
                            First_name = "John",
                            Last_name = "Doe",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PIN = "hjPe23Lmn4",
                            First_name = "Rand",
                            Last_name = "al'Thor",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PIN = "oopq34dda5",
                            First_name = "Paul",
                            Last_name = "Atreides",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PIN = "lkas45mkp6",
                            First_name = "Frodo",
                            Last_name = "Baggins",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PIN = "mnet56sda7",
                            First_name = "James",
                            Last_name = "Holden",
                            Time_created = new DateTime(2025, 12, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Coursera_Exercise.Models.StudentCourse", b =>
                {
                    b.Property<string>("Student_pin")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Course_id")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Completion_Date")
                        .HasColumnType("date");

                    b.HasKey("Student_pin", "Course_id");

                    b.HasIndex("Course_id");

                    b.ToTable("StudentsCourse");

                    b.HasData(
                        new
                        {
                            Student_pin = "hjPe23Lmn4",
                            Course_id = 3
                        },
                        new
                        {
                            Student_pin = "mnet56sda7",
                            Course_id = 3,
                            Completion_Date = new DateOnly(2023, 12, 9)
                        },
                        new
                        {
                            Student_pin = "mnet56sda7",
                            Course_id = 4,
                            Completion_Date = new DateOnly(2023, 12, 9)
                        },
                        new
                        {
                            Student_pin = "lkas45mkp6",
                            Course_id = 3
                        },
                        new
                        {
                            Student_pin = "hjPe23Lmn4",
                            Course_id = 5
                        },
                        new
                        {
                            Student_pin = "hjPe23Lmn4",
                            Course_id = 1
                        },
                        new
                        {
                            Student_pin = "sahh12KJF3",
                            Course_id = 2
                        },
                        new
                        {
                            Student_pin = "sahh12KJF3",
                            Course_id = 4
                        },
                        new
                        {
                            Student_pin = "mnet56sda7",
                            Course_id = 5
                        },
                        new
                        {
                            Student_pin = "oopq34dda5",
                            Course_id = 4,
                            Completion_Date = new DateOnly(2023, 12, 9)
                        },
                        new
                        {
                            Student_pin = "lkas45mkp6",
                            Course_id = 1
                        },
                        new
                        {
                            Student_pin = "mnet56sda7",
                            Course_id = 2
                        },
                        new
                        {
                            Student_pin = "sahh12KJF3",
                            Course_id = 3,
                            Completion_Date = new DateOnly(2023, 12, 9)
                        },
                        new
                        {
                            Student_pin = "hjPe23Lmn4",
                            Course_id = 4,
                            Completion_Date = new DateOnly(2023, 12, 9)
                        },
                        new
                        {
                            Student_pin = "mnet56sda7",
                            Course_id = 1
                        });
                });

            modelBuilder.Entity("Coursera_Exercise.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.Course", b =>
                {
                    b.HasOne("Coursera_Exercise.Models.Instructor", "_Instructor")
                        .WithMany()
                        .HasForeignKey("Instructor_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Instructor");
                });

            modelBuilder.Entity("Coursera_Exercise.Models.StudentCourse", b =>
                {
                    b.HasOne("Coursera_Exercise.Models.Course", "_Course")
                        .WithMany()
                        .HasForeignKey("Course_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Coursera_Exercise.Models.Student", "_Student")
                        .WithMany()
                        .HasForeignKey("Student_pin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_Course");

                    b.Navigation("_Student");
                });
#pragma warning restore 612, 618
        }
    }
}
