@HostAddress = https://localhost:7132
@Auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJTaW1lb25nbWlsZXYiLCJqdGkiOiJlN2ZiNzVhZC1hNDliLTQzNzMtYmYyNS0xOGQyNzc2YmZhMWEiLCJleHAiOjE3NjUyOTExNjEsImlzcyI6ImxvY2FsaG9zdDo3MTMyIiwiYXVkIjoibG9jYWxob3N0OjcxMzIifQ.rWzZ7M113YTuE88gM8wdU6mL5Dgrj-JbWAofUfI2EZc

GET {{HostAddress}}/api/blocks/
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/blocks/3
Accept: application/json
Authorization: {{Auth}}

###

POST {{HostAddress}}/api/blocks
Content-Type: application/json
Authorization: {{Auth}}
{
  "Name": "Lego",
  "Code": "3352"
}

###

PUT {{HostAddress}}/api/blocks/4
Content-Type: application/json
Authorization: {{Auth}}
{
  "Id": 4,
  "Name": "Globglobgabgalab",
  "Code": "3372"
}

###


DELETE {{HostAddress}}/api/blocks/5
Authorization: {{Auth}}

###



POST {{HostAddress}}/api/systems
Content-Type: application/json
Authorization: {{Auth}}
{
  "Name":"System 7",
  "Code":"2342",
  "Parent" : 6
}

###

GET {{HostAddress}}/api/systems
Authorization: {{Auth}}

###

DELETE {{HostAddress}}/api/systems/3
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/systems/3
Authorization: {{Auth}}

###
GET {{HostAddress}}/api/systems/6/name
Authorization: {{Auth}}

###
PUT {{HostAddress}}/api/systems/1
Content-Type: application/json
Authorization: {{Auth}}
{
  "Name":"System 1",
  "Code":"362"
}

###

GET {{HostAddress}}/api/TechnicalServices
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/TechnicalServices/2
Accept: application/json
Authorization: {{Auth}}

###

POST {{HostAddress}}/api/TechnicalServices
Content-Type: application/json
Authorization: {{Auth}}
{
  "Id": 6,
  "Name": "Service 4",
  "Description": "I am Groot",
  "Blocks": [2,4],
  "Systems": [3,2],
  "ResponsiblePersons":[2,3],
  "TimeOfCreation":"2025-12-05T11:21:57.7559033+02:00"
}

###

PUT {{HostAddress}}/api/TechnicalServices/1
Content-Type: application/json
Authorization: {{Auth}}
{
  "Id":1,
  "Name": "Service 01",
  "Description": "Hello There",
  "Blocks": [1,4],
  "Systems":[2,1],
  "ResponsiblePersons":[5,1]
}

###
DELETE {{HostAddress}}/api/TechnicalServices/4
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/employees
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/employees/4
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/employees/pin=33215523
Accept: application/json
Authorization: {{Auth}}

###

POST {{HostAddress}}/api/employees
Content-Type: application/json
Authorization: {{Auth}}
{
  "FirstName":"Name",
  "Surname":"Surname",
  "LastName":"Family",
  "PIN":"2245531235"
}
###

PUT {{HostAddress}}/api/employees/16
Content-Type: application/json
Authorization: {{Auth}}
{
  "FirstName":"Michael",
  "Surname":"Williams",
  "LastName":"John"
}
###

DELETE {{HostAddress}}/api/employees/5
Accept: application/json
Authorization: {{Auth}}

###

POST {{HostAddress}}/api/technicalServices/1/blocks/1
Accept: application/json
Authorization: {{Auth}}

###

DELETE {{HostAddress}}/api/technicalServices/2/blocks/3
Accept: application/json
Authorization: {{Auth}}

###

  
POST {{HostAddress}}/api/technicalServices/3/systems/1
Accept: application/json
Authorization: {{Auth}}

###

DELETE {{HostAddress}}/api/technicalServices/3/systems/2
Accept: application/json
Authorization: {{Auth}}

###

  POST {{HostAddress}}/api/technicalServices/3/ResponsiblePersons/verification/2
Accept: application/json
Authorization: {{Auth}}

###

DELETE {{HostAddress}}/api/technicalServices/3/ResponsiblePersons/creation
Accept: application/json
Authorization: {{Auth}}

###

GET {{HostAddress}}/api/report
Content-type: application/json
Authorization: {{Auth}}
{
 
}

###
POST {{HostAddress}}/api/users/register
Content-type: application/json
{
  "Username": "Simeongmilev",
  "Email":"Example@mail.mail",
  "Password":"Pass"
}

###
POST {{HostAddress}}/api/users/login
Content-type: application/json
{
  "Username":"Simeongmilev",
  "Email":"",
  "Password":"Pass"
}