@HostAddress = http://localhost:5119

GET {{HostAddress}}/api/blocks/
Accept: application/json

###

GET {{HostAddress}}/api/blocks/3
Accept: application/json

###

POST {{HostAddress}}/api/blocks
Content-Type: application/json

{
  "Name": "Lego",
  "Code": "3352"
}

###

PUT {{HostAddress}}/api/blocks/4
Content-Type: application/json

{
  "Id": 4,
  "Name": "Globglobgabgalab",
  "Code": "3372"
}

###


DELETE {{HostAddress}}/api/blocks/5

###



POST {{HostAddress}}/api/systems
Content-Type: application/json

{
  "Id" : 7,
  "Name":"System 6",
  "Code":"4573",
  "Parent" : 7
}

###

GET {{HostAddress}}/api/systems

###

DELETE {{HostAddress}}/api/systems/4

###

GET {{HostAddress}}/api/systems/3

###

PUT {{HostAddress}}/api/systems/1
Content-Type: application/json

{
  "Id":1,
  "Name":"dfhndskfhlas",
  "Code":"332",
  "Parent":5
}

###

GET {{HostAddress}}/api/TechnicalServices
Accept: application/json

###

GET {{HostAddress}}/api/TechnicalServices/2
Accept: application/json

###

POST {{HostAddress}}/api/TechnicalServices
Content-Type: application/json
{
  "Id": 6,
  "Name": "Service 4",
  "Description": "I am Groot",
  "Blocks": [2,4],
  "Systems": [3,2],
  "ResponsiblePersons":[2,3],
  "TimeOfCreation":"2025-12-05T11:21:57.7559033+02:00"
}

###

PUT {{HostAddress}}/api/TechnicalServices/1
Content-Type: application/json
{
  "Id":1,
  "Name": "Service 01",
  "Description": "Hello There",
  "Blocks": [1,4],
  "Systems":[2,1],
  "ResponsiblePersons":[5,1]
}

###
DELETE {{HostAddress}}/api/TechnicalServices/4
Accept: application/json

###

GET {{HostAddress}}/api/employees
Accept: application/json

###

GET {{HostAddress}}/api/employees/4
Accept: application/json

###

POST {{HostAddress}}/api/employees
Content-Type: application/json
{
  "Id": 6,
  "FirstName":"Name",
  "Surname":"Surname",
  "LastName":"Family",
  "PIN":"2245531235"
}
###

PUT {{HostAddress}}/api/employees/3
Content-Type: application/json
{
  "Id":3,
  "FirstName":"Hans",
  "Surname":"Christian",
  "LastName":"Anderson",
  "PIN":"33215523"
}
###

DELETE {{HostAddress}}/api/employees/5
Accept: application/json

###